// is necessary to download 'REST Client' extension

post http://localhost:3000/events
Content-Type: application/json

{
    "title": "Unite summit",
    "details": "Um evento para quem é apaixonado por programação!",
    "maximumAttendees": 100
}

###

// is necessary to get a valid eventId in prisma database
// you can run in terminal 'npx prisma studio' to see all registers
POST http://localhost:3000/events/9a1e94ea-f52d-405d-9ae7-671721b22ee8/attendees
Content-Type: application/json

{
  "name": "Melissa Lopes",
  "email": "melissa@rocketseat.com.br"
}

###

GET http://localhost:3000/events/9a1e94ea-f52d-405d-9ae7-671721b22ee8

###

GET http://localhost:3000/attendees/3/badge

###

GET http://localhost:3000/attendees/4/check-in

###